### ISSUE TITLE
Dashing is not working !

### ISSUE THREAD

**Issue by thomaspons** [fabiocaseri/dashing-js#10]
I 've run the sample dashboard and the data don't appear  !!

Is this module doesn't work or i missing something here ?

**Comment by constantx** [comment]
hi @thomaspons,

you can try https://github.com/constantx/dashing-node see if it works for you? It's generated from dashing-js

**Comment by thomaspons** [comment]
Same thing !

 I'm behind a corporate proxy ...

It doesn't work ...

**Comment by fabiocaseri** [comment]
What do you mean with "behind a corporate proxy"?
Dashing can run on localhost.

**Comment by arabold** [comment]
I have an issue with dashing-js not updating with data from my jobs. I've just downloaded and installed it according to the README. I can see the dashboard and I can run jobs. I can also see the jobs POSTing information to the dashboard in the nodejs log. However, the data is never shown in the dashboard itself. 

I need to admit that I'm using a Windows environment for this test. I haven't tried it on Ubuntu yet.

**Comment by fabiocaseri** [comment]
Can you post a gist with the code of the job sending the data and the widget receiving it?

**Comment by arabold** [comment]
It works fine on Ubuntu. Just tried it and all data is shown as expected. So it seems it relates to Windows... I'm just using the standard installation without customization. Not even the "sample" dashboard is working on Windows. It just never updates and shows no data.

**Comment by fabiocaseri** [comment]
I tried on Windows XP and Windows 7 and it just works. Are you on Win 8 ?

**Comment by arabold** [comment]
Nope. I'm on Win 7. Nothing in the browser console, nothing on command line. Everything seems to work but it doesn't. I'm not using a proxy, dashing-js runs on localhost with default config, using Chrome browser (I think IE isn't even working properly). Basically everything I've done is the same on Windows and Ubuntu. The difference is that it works on Ubuntu, but doesn't work on Windows... wth!

**Comment by arabold** [comment]
Just a short update here: I still didn't get it to work on Windows. However, it runs smooth on Ubuntu and I was able to setup my first custom dashboard which pulls data from a MySQL db. I've also found that there are some small mistakes in the default setup such as an error in the .ejs template when creating a new dashboard. I'll look some more into dashing-js in general and might provide pull-requests in future. I'd prefer dashing-js over the original one as we're using nodejs extensively here but no ruby at all. Thanks for your efforts!

**Comment by fabiocaseri** [comment]
I usually run it on Linux, but before releasing 0.1.2 I tried on OS X and Win7 the sample and sampletv dashboards, both work fine. Without more details I can't help...

The default setup use jade as template engine, so I didn't test ejs so well.
You can open a new issue reporting the mistake.
Thanks!

**Comment by arabold** [comment]
Another quick update: I haven't had time to really play with it today, but I found a "workaround" to get dashing-js work on my Windows system. In the /events route I set the time out 1 (`req.socket.setTimeout(1);`). This will make the dashboard update properly as on Ubuntu. My assumption is that node on Windows might behave a little bit different in my case than node on Ubuntu, but I'm too new to really have an idea why and what's going on. I'll spend more time over the next couple of days.

**Comment by arabold** [comment]
http://stackoverflow.com/questions/12978466/javascript-eventsource-sse-not-firing-in-browser

> Be warned.. if your client uses any kind of anti-virus software which intercepts web requests, it may cause problems here. In this case, Sophos Endpoint Security, which provides enterprise grade anti-virus and firewall protection has a feature called web protection. Within this features is an option to scan downloads; it seems that the SSE connection is treated as a download and thus not released to the browser until the connection is closed and the stream received to scan. Disabling this option cures the problem. I have submitted a bug report but other anti-virus systems may do the same.

That's _exactly_ my problem. Sophos is to blame.

**Comment by fabiocaseri** [comment]
Great! So does it work without problems now?

**Comment by arabold** [comment]
I can't disable Sophos on my work machine but I accept this as the answer to my issue. However, I still would want to have people in our office be able to utilize the dashboard so I need to find a workaround. Right now I'm thinking of setting a timeout in the socket, e.g. 30 seconds, or to simply close the connection whenever data was sent. This wouldn't be perfect of course but should at least work.

**Comment by fabiocaseri** [comment]
Ok, closing this.
