### ISSUE TITLE
Editing the EJS template instead of the Jade template?

### ISSUE THREAD

**Issue by ufasoli** [fabiocaseri/dashing-js#22]
Hi,
I'm sorry if the question seems quite stupid but I do not have any experience using NodeJS.
I need to do a simple dashboard for my company, when running the sample dashboard I can see that under dashboards there are every-time 2 files one with the .ejs extension and one with the .jade extension.

Since I'm more familiar with the HTML syntax of EJS rather than the Jade syntax I wanted to edit the contents of the EJS template but whenever I make changes on the EJS template nothing happens on the dashboard whereas whenever I change anything on the Jade template the changes are visible.

Is there a particular reason for having these 2 formats? is it possible to only edit the EJS template and not the Jade one?

thanks

Ulises

**Comment by guicattani** [comment]
Any help on this? How did you solve it?

**Comment by guicattani** [comment]
Solved. You need to use `dashing-js start -e ejs`
